version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    assignees:
      - "alexmatiasas"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"