# Task runner: https://just.systems
default:
    @just --list

build:
    go build -o bin/server ./cmd/server

run: build
    ./bin/server

test:
    go test -race ./...

lint:
    golangci-lint run

fmt:
    gofmt -w .
