# Task runner: https://just.systems
default:
    @just --list

build:
    cargo build

run *ARGS:
    cargo run -- {{ARGS}}

test *ARGS:
    cargo test {{ARGS}}

lint:
    cargo clippy --all-targets -- -D warnings

fmt:
    cargo fmt --all
